data:
  dataset:
    train_path: ../data/train-v2.0.json
    dev_path: ../data/dev-v2.0.json
  dataset_h5: ../data/squad_glove.h5

  embedding_path: /home/ivania/Cursos/deep_learning/Match-LSTM/data/glove.6B.zip
  kg_embeddings_vec_path: /home/ivania/Cursos/deep_learning/DNN-Project/entity_embeddings.tsv
  kg_patterns2id_path: /home/ivania/Cursos/deep_learning/DNN-Project/kg_patterns2id.json

  model_path: ../data/model-weight.pt
  checkpoint_path: ../data/checkpoint

global:
  random_seed: 123
  num_data_workers: 5   # for data loader
  model: match-lstm  # 'match-lstm', 'match-lstm+', 'r-net', 'm-reader' or 'base'
                      # Note that 'base' model is customized by base_model.yaml

preprocess:
  word_embedding_size: 300
  kg_embedding_size: 32
  ignore_max_len: 600 # in train data, context token len > ignore_max_len will be dropped
  use_char: False
  use_pos: True
  use_ent: False
  use_em: False
  use_em_lemma: False

train:
  batch_size: 32
  valid_batch_size: 32
  epoch: 30
  enable_cuda: False

  optimizer: 'adamax'  # adam, sgd, adamax, adadelta(default is adamax)
  learning_rate: 0.002  # only for sgd
  clip_grad_norm: 5

test:
  batch_size: 32
  enable_cuda: False